<?php

namespace Tests\Feature;

use App\Models\Admin;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Tests\TestCase;

class ProductModuleTest extends TestCase
{
    use RefreshDatabase;

    public function test_admin_can_create_product(): void
    {
        $admin = Admin::create([
            'name'      => 'Test Admin',
            'email'     => 'admin@example.com',
            'password'  => bcrypt('password123'),
            'is_active' => true,
        ]);

        $role = Role::create(['name' => 'super-admin', 'guard_name' => 'admin']);
        $role->givePermissionTo([
            Permission::firstOrCreate(['name' => 'product.view', 'guard_name' => 'admin']),
            Permission::firstOrCreate(['name' => 'product.create', 'guard_name' => 'admin']),
            Permission::firstOrCreate(['name' => 'product.edit', 'guard_name' => 'admin']),
            Permission::firstOrCreate(['name' => 'product.delete', 'guard_name' => 'admin']),
        ]);
        $admin->assignRole($role);

        // ✅ Leaf category (no children) — required since products can
        // only be assigned to categories without sub-categories.
        $category = Category::create([
            'name'        => 'Electronics',
            'slug'        => 'electronics',
            'description' => 'Test category',
            'parent_id'   => null,
            'is_active'   => true,
            'sort_order'  => 1,
        ]);

        $response = $this->actingAs($admin, 'admin')->post(route('admin.ecommerce.product.store'), [
            // ❌ 'sku' removed — auto-generated by ProductService, never user-submitted
            'name'                => 'Test Product',
            'category_id'         => $category->id,
            'price'               => '199.99',
            // ❌ 'sale_price' replaced — our schema uses discount_type/discount_value, not sale_price
            'discount_type'       => 'fixed',
            'discount_value'      => '20.00',
            'purchase_price'      => '150.00',
            'stock_quantity'      => 10,
            'low_stock_threshold' => 3,
            'is_active'           => 'active',   // resolveBoolean() handles this string
            'is_featured'         => 'inactive', // resolveBoolean() treats this as false
            'short_description'  => 'A test product',
            'description'        => 'Detailed description',
            // ✅ tags must be an array, not comma-separated string
            'tags'                => ['test', 'gadget'],
            // ❌ 'sort_order' removed — that's a Category field, Product has no sort_order column
        ]);

        $response->assertRedirect(route('admin.ecommerce.product.index'));
        $response->assertSessionHas('success');

        // ✅ Verify product created with correct core fields
        $this->assertDatabaseHas('products', [
            'name'        => 'Test Product',
            'category_id' => $category->id,
            'price'       => '199.99',
            'is_active'   => true,
            'is_featured' => false,
        ]);

        $product = Product::where('name', 'Test Product')->first();

        // ✅ Verify SKU was auto-generated using category-prefix format
        // Category "Electronics" -> prefix "ELE", first product -> "ELE-00001"
        $this->assertNotNull($product->sku);
        $this->assertEquals('ELE-00001', $product->sku);

        // ✅ Verify slug was auto-generated from name
        $this->assertEquals('test-product', $product->slug);

        // ✅ Verify tags were created and attached (create-on-the-fly behavior)
        $this->assertDatabaseHas('tags', ['slug' => 'test']);
        $this->assertDatabaseHas('tags', ['slug' => 'gadget']);
        $this->assertDatabaseHas('product_tag', ['product_id' => $product->id]);
        $this->assertCount(2, $product->tags);
    }

    public function test_product_cannot_be_assigned_to_parent_category_with_children(): void
    {
        $admin = Admin::create([
            'name'      => 'Test Admin',
            'email'     => 'admin@example.com',
            'password'  => bcrypt('password123'),
            'is_active' => true,
        ]);

        $role = Role::create(['name' => 'super-admin', 'guard_name' => 'admin']);
        $role->givePermissionTo([
            Permission::firstOrCreate(['name' => 'product.view', 'guard_name' => 'admin']),
            Permission::firstOrCreate(['name' => 'product.create', 'guard_name' => 'admin']),
        ]);
        $admin->assignRole($role);

        // Parent category
        $parent = Category::create([
            'name'      => 'Furniture',
            'slug'      => 'furniture',
            'parent_id' => null,
            'is_active' => true,
        ]);

        // Child category (makes $parent ineligible for product assignment)
        Category::create([
            'name'      => 'Chairs',
            'slug'      => 'chairs',
            'parent_id' => $parent->id,
            'is_active' => true,
        ]);

        $response = $this->actingAs($admin, 'admin')->post(route('admin.ecommerce.product.store'), [
            'name'                => 'Invalid Product',
            'category_id'         => $parent->id, // ❌ Has children — should fail validation
            'price'               => '99.99',
            'stock_quantity'      => 5,
            'low_stock_threshold' => 2,
            'is_active'           => 'active',
        ]);

        $response->assertSessionHasErrors('category_id');
        $this->assertDatabaseMissing('products', ['name' => 'Invalid Product']);
    }
}